### ISSUE TITLE
[Possible Requests]

### ISSUE THREAD

**Issue by MagnetStryker** [ssrando/ssrando#145]
Hello,

1.
I was playing the rando, but while I was flying I got stopped alot by the tornedo's.
Is to possible to remove them?

2.
The Peater/Patrice's Cristals are tedious the unlock.
Is there a possibility to set the progressing of the side quest higher?
If thats not possible maybe a bed in the bazaar so we don't have to go trought multiple loading zones to advance the day counter.

**Comment by yannl35133** [comment]
First and foremost, requests are usually done in the [Discord server](discord.ssrando.com) so non-techy players can make their own, so to keep them in a single place please do so as well.

1. Tornadoes were recently tweaked so they shouldn't be as impossible to avoid as they were. Do they still annoy you that much after the patch ?
2. This is arguably what makes it interesting. This is also the reason it has its own setting to remove it (from the useful checks). I guess you could bring this up in Discord to launch a discussion (I think adding a bed would be considered too great a change though)

**Comment by MagnetStryker** [comment]
For the tornadoes, because of the increased flying speed I don't have that mutch time to react and the sometime appear right in front of me.

For the second requet I'll post it in the discord for discussion
