### ISSUE TITLE
[Can't run the randomizer

### ISSUE THREAD

**Issue by FaFou01** [ssrando/ssrando#151]
Hello, 
I'm trying to run the rundomizer after having installed it from the source, but it doesn't work, it's stuck because it can't find the module mlzss11. I think the issue comes from the step with "pip install -r requirements.txt". And i'm in master version btw.
Can you help me please ?

**Comment by yannl35133** [comment]
You mean `nlzss11` ? What system are you using ?

**Comment by FaFou01** [comment]
Yes nlzss11.
I'm using Windows 10.

Thanks for your fast reply

Le mer. 26 janv. 2022 à 23:31, yannl35133 ***@***.***> a
écrit :

**Comment by yannl35133** [comment]
For all lines in `requirements.txt`, do `pip install ${package}` (you can drop the version constraints) and tell me which don't work

**Comment by FaFou01** [comment]
I don't really understood what you Nantes me to do but it seems that's
PyYAML and PySide6 are installée, but it stops when it truc to install
nlzss11 et future

Le mer. 26 janv. 2022 à 23:41, yannl35133 ***@***.***> a
écrit :

**Comment by yannl35133** [comment]
Great correcteur orthographique I see.
What's the error message on `pip install nlzss11` ?

**Comment by lepelog** [comment]
what python version are you using? Unfortunately the dependency isn't compiled for anything later than 3.8

**Comment by FaFou01** [comment]
[image: image.png]
this (enjoy)

Le mer. 26 janv. 2022 à 23:49, yannl35133 ***@***.***> a
écrit :

**Comment by FaFou01** [comment]
i'm using 3.10 python. should i use 3.8 instead ?

**Comment by yannl35133** [comment]
The image was not sent. Python 3.10 should be fine (it is for me but I speak from Linux)

**Comment by lepelog** [comment]
No, use 3.8 if possible, as I said certain dependencies are not yet compatible with that version on windows

**Comment by yannl35133** [comment]
Right, I'm dumb; you'll need 3.8 or less on Windows for now.
Note that you can also download the packaged randomizer from ssrando.com if you don't want to bother with running from source

**Comment by FaFou01** [comment]
you're were right, it worked with python 3.8. thanks a lot.

**Comment by FaFou01** [comment]
hi
i succeded to install the randomizer, but now i can't extract the iso
because i think there is a problem with the certificate (i got the error
"ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate
verify failed: certificate has expired (_ssl.c:1131)")
Do you know where i can find a good iso which work for the randomizer ?

**Comment by lepelog** [comment]
That's not an issue with the ISO. We also won't be able to help you find an ISO due to copyright laws.

Can you try `pip install certifi`? There seems to be a problem with windows and outdated certificate lists.

**Comment by FaFou01** [comment]
i tried it. it installed certifi, but doesn't help unfortunatly

**Comment by FaFou01** [comment]
i don't know what's the problem, do you have an idea to fix that ?
