### ISSUE TITLE
Locked out of Key Piece?

### ISSUE THREAD

**Issue by gg30433043** [ssrando/ssrando#350]
[SS Random 116134 - Spoiler Log.txt](https://github.com/ssrando/ssrando/files/10713051/SS.Random.116134.-.Spoiler.Log.txt)
This is my spoiler. I have gotten the key pieces from every location but seemingly only have four. I'm not sure where I missed the last one but Im certain thats its between the letter or the gift. I think because I took so long to go back to owlan he no longer is giving me his item. Am I mistaken or is it bugged?

**Comment by YourAverageLink** [comment]
When you talk to Owlan, does he say something about researching plant life? There's a patch such that, after you get his item, he will say something like that to hint towards the existence of Owlan's Crystals (the Kikwi delivery).

**Comment by gg30433043** [comment]
As of right now, when I speak to him outside he mentions the research, but when I speak to him inside he only says "How's the search for Zelda", or "You should get some rest" if it's night. However, I'm looking for the gift he gives you at the beginning which holds the last key piece I need for the earth temple(not his crystals from the delivery). Should I use a save editor and give myself this key piece since I seem to not be able to acquire it?

**Comment by yannl35133** [comment]
There are no known instances of either Owlan's Gift or Cawlin's Letter being locked from doing other stuff. What did you do ? What does Cawlin say ? Are you sure you got both pieces from Batreaux and the one from Beedle ?

**Comment by gg30433043** [comment]
I'm not sure exactly which piece is glitched since I am just realizing this a couple hours into my run. I have over 70 crystals, so I know I got both from Batreaux and I bought one from Beedle(Batreaux had both so maybe it glitched and didn't give me one). I don't remember getting Owlan's Gift, but he isn't giving me anything now. And Karane and Pipit are standing in the classroom as I completed their side quest. Not sure what I did wrong, but I only have four of the five pieces.

**Comment by yannl35133** [comment]
Is he not standing next to the Academy door (as well) ? I am more inclined to think Cawlin's Letter is the one you would have been locked out of

**Comment by gg30433043** [comment]
There is one instance of him standing outside his room and one instance of him crying in goose's room. The letter on the item screen is also checked if that means anything.

**Comment by yannl35133** [comment]
What did you do regarding Cawlin's Letter quest ? Did you talk to the toilet hand at night ?

**Comment by gg30433043** [comment]
I gave it to karane since I did not see the toilet hand at night.

**Comment by yannl35133** [comment]
Did you talk to the toilet hand at night ? If not, can you now ?

**Comment by gg30433043** [comment]
I walked to the door and the ghost said forget about the paper and is not in the restroom.
