### ISSUE TITLE
Dungoen finished exit teleport

### ISSUE THREAD

**Issue by MagnetStryker** [ssrando/ssrando#412]
Hello,
I'm doing a rando with dungeon entrances randomized;
I do not have access to the sand sea but got teleported there after doing the sandship;

I could not light the flame because I didn't have the goddess sword yet.
When i came bac with the goddess sword and lit the flame it promted me to save and teleported me to the docks at the start of sand sea.
This area is out of logic because I don't have the key to enter the sand sea yet.

ANf5GBFOAAAAAAAAAEAEBwACAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADUgAAAAAAAAAAAAAAABIA==#165147

rando version V1.4.1

**Comment by CovenEsme** [comment]
Thanks for reporting this. I've managed to reproduce the bug you've encountered and I'll have a look at creating a fix for it.

In case you're worried, your seed should still be beatable. You are not expected to use the incorrect teleport behaviour to gain access to the Lanayru Sand Sea. You can safely continue to play the seed :p

**Comment by MagnetStryker** [comment]
teh Goddess sword was needed for the cave key. I got it 5 min after the wrong warp :p

**Comment by CovenEsme** [comment]
Sorry it took so long but this issue is fixed with #479
