### ISSUE TITLE
iso integrity checks & extract file checks

### ISSUE THREAD

**Issue by lepelog** [ssrando/ssrando#52]
- verify the iso when it's extracted
- verify that all the files are in modified-extract before every randomization (prevents errors on bad extracts)

**Comment by CovenEsme** [comment]
Is this still relevant?

**Comment by lepelog** [comment]
The first point is done, but the second point *could* be relevant if someone aborts the extraction process mid way, but I doubt that happens often enough to justify checking all files every time
