### ISSUE TITLE
Add more Arrow drops

### ISSUE THREAD

**Issue by lepelog** [ssrando/ssrando#59]
In swordless, Arrows can be the primary source of damage, but pots with arrows are really rare in vanilla.
Places to add arrows to:
- Sealed Temple
- Faron Woods (probably next to first statue)
- Skyview (next to first statue)
- Mogma Turf (next to statue)
- next to ET entrance statue
- next to fist lanayru statue
- next to first LMF statue

**Comment by CovenEsme** [comment]
Added as of #206 and #226
