### ISSUE TITLE
WBFS to Iso

### ISSUE THREAD

**Issue by TopHatMan** [ssrando/ssrando#86]
Can we get iso support , I can never loead any WBFS with my sd card on my hacked wii, I got softmod and hardmod. So I can just run iso. I tried converting it to iso. The game would not load.

**Comment by lepelog** [comment]
That's a weird issue, do other games work as ISO? I don't see a reason why the wbfs converted to ISO wouldn't work
To generate an ISO directly from the randomizer files open powershell, go to the rando directory that has `modified-extract` and run `.\wit-v3.03a-r8245-cygwin\bin\wit.exe -P COPY modified-extract disc.iso`

**Comment by TopHatMan** [comment]
Does not work   and I got hardmod thats odd

**Comment by CovenEsme** [comment]
#440
